version: '3'
services:

  mongo:
    image: mongo
    container_name: gontacts-mongo
    restart: always

  gin:
    build: .
    container_name: gontacts-gin
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - "MONGO_URL=mongodb://mongo:27017/gontactss"
      - "ADDR=0.0.0.0:8000"
    env_file:
      - ".env"